from core import typecheck as typecheck

def input_path(message: str = 'Enter a file name: ') -> str: ...
def format_return_char(string: str) -> str: ...
def add_suffix(file_path: str, suffix: str) -> str: ...