from typing import Callable, Iterable

from base_utils.typecheck import type_check as type_check

def join(funcs: list[Callable]) -> Callable: ...
def flatten(data: Iterable[Iterable | object]) -> list: ...
def find_all_file(path: str) -> list[str]: ...
def find_all_file_by_suffix(path: str, suffix: str) -> list[str]: ...
def find_all_file_by_prefix(path: str, prefix: str) -> list[str]: ...
def get_subfolders(path: str) -> list[tuple[str, str]]: ...
